# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f237663118ef837a811cb20ea406a6c27bb1526d6b4880595a2fbca58c98e5cb5373936b73ef98f7385151ab1420cdcd040c76f3756ac2e5dacc323d17e80f61

test:
  secret_key_base: 2d60196b4e9646dabad9129b9b67e566e4e3c809896233bf8c26686357a5829d2d017205cdee3ea4697dda16ced57ba60dc7c3428b7f305ce0ca5fffd6b4a28a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
